name: CI
on:
  push:
    branches:
      - main
    paths:
      - debian/**
      - .github/workflows/ci.yaml
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - version: 11.6
          - version: 10.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Semver Version
        id: get-version
        run: |
          npm install -g semver
          echo "version=$(semver --coerce ${{ matrix.version }})" >> $GITHUB_OUTPUT

      - name: Semver Parse
        uses: terradatum/semver-action@main
        id: semver
        with:
          version: ${{ steps.get-version.outputs.version }}

      - name: Print Version
        run: |
          echo "version: ${{ steps.semver.outputs.version }}"
          echo "major: ${{ steps.semver.outputs.major }}"
          echo "minor: ${{ steps.semver.outputs.minor }}"
          echo "patch: ${{ steps.semver.outputs.patch }}"

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/debian
          tags: |
            type=raw,value=${{ matrix.version }}
            type=raw,value=${{ steps.semver.outputs.major }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:debian"
          push: false
          build-args: |
            VERSION=${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
