name: CI
on:
  push:
    branches:
      - main
    paths:
      - debian/**
      - .github/workflows/ci.yaml
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - version: 11.6
            tags: [11.6, 11, latest]
          - version: 10.3
            tags: [10.3, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Semver Parse
      #   uses: apexskier/github-semver-parse@v1
      #   id: semver
      #   with:
      #     version: ${{ env.version }}

      - name: Print Version
        run: |
          echo "version: ${{ matrix.version }}"
          echo "tags: ${{ matrix.tags }}"
          # echo "env version: ${{ env.version }} "
          # echo "version: ${{ steps.semver.outputs.version }}"
          # echo "major: ${{ steps.semver.outputs.major }}"
          # echo "minor: ${{ steps.semver.outputs.minor }}"
          # echo "patch: ${{ steps.semver.outputs.patch }}"
          # echo "prerelease: ${{ steps.semver.outputs.prerelease }}"
          # echo "build: ${{ steps.semver.outputs.build }}"

      # - name: Docker Metadata
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: |
      #       ghcr.io/${{ github.repository_owner }}/debian
      #     tags: |
      #       type=match,enable=true,pattern=debian/v?(.*),group=1

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: "{{defaultContext}}:debian"
      #     push: false
      #     tags: ${{ steps.meta.outputs.tags }}
      #     tags: |
      #       ghcr.io/${{ github.repository_owner }}/debian:${{ matrix.tags }}
